### ISSUE TITLE
IllegalStateException in MarshmallowReprintModule.java

### ISSUE THREAD

**Issue by pgrpmichel** [ajalt/reprint#29] opened 2017-12-22 15:49 UTC
v3.1.0

**IllegalStateException** in **MarshmallowReprintModule.java**: 

caused by java.lang.IllegalStateException : _Failed parsing settings file: /data/system/users/0/settings_fingerprint.xml_

**Comment by ajalt** [comment] 2017-12-22 16:51
Can you give me more information? What's the full stack trace, what device do you see that on, what version of android?

**Comment by pgrpmichel** [comment] 2017-12-22 18:02
Issue appears to be happening on several Android versions and Samsung Devices and one HTC 10:
 
HTC 2PS64 10               v8.0
SM-N920V                     v7.0
SM-G920T                     v7.0
SAMSUNG-SM-G928A v7.0
SM-G925V                     v6.0.1

**Comment by pgrpmichel** [comment] 2017-12-22 18:05
Exception:     java.lang.IllegalStateException
Ex. Message:   Failed parsing settings file: /data/system/users/0/settings_fingerprint.xml
Thread:        Thread[main,5,main]
Memory Usage:  7 / 3764 MB (0%)

Original stack trace:
======================
java.lang.RuntimeException : Unable to start activity ComponentInfo{...SplashActivity}: java.lang.IllegalStateException: Failed parsing settings file: /data/system/users/0/settings_fingerprint.xml
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2904)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2979)
        at android.app.ActivityThread.-wrap11(Unknown Source)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
        Caused by: java.lang.IllegalStateException : Failed parsing settings file: /data/system/users/0/settings_fingerprint.xml
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.os.Parcel.readException(Parcel.java:1897)
        at android.hardware.fingerprint.IFingerprintService$Stub$Proxy.hasEnrolledFingerprints(IFingerprintService.java:498)
        at android.hardware.fingerprint.FingerprintManager.hasEnrolledFingerprints(FingerprintManager.java:774)
        at com.github.ajalt.reprint.module.marshmallow.MarshmallowReprintModule.hasFingerprintRegistered(MarshmallowReprintModule.java:165)
        at com.github.ajalt.reprint.core.ReprintInternal.hasFingerprintRegistered(ReprintInternal.java:73)
        at com.github.ajalt.reprint.core.Reprint.hasFingerprintRegistered(Reprint.java:78)
        at ...
        at ...
        at ...
        at android.app.Activity.performCreate(Activity.java:6986)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1232)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2857)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2979)
        at android.app.ActivityThread.-wrap11(Unknown Source)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:180)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)

**Comment by ajalt** [comment] 2017-12-22 18:45
Interesting. It's definitely not a bug in Reprint, so the best we can do is catch it. I'm not seeing that crash on any devices. How are you using reprint?

**Comment by pgrpmichel** [comment] 2017-12-22 20:32
Indeed.  I agree, this is something that bubbles up from android.hardware.fingerprint.  I couldn't find anything tracking this specific issue in Android.  I did come across some info on issues with some OEMs breaking the APIs here for certain devices that don't have sensors, but nothing on the parse issue.  

We are using reprint for a login feature in our app.  When this crash occurs, it's in our launcher when we try to see if the device supports and if it is set up for fingerprint (so we can add the feature to our login screen and settings menu).  Were you looking for more specifics?

**Comment by ajalt** [comment] 2017-12-22 21:33
I'll definitely catch the exception and return false. The fact that I've never seen this crash makes me wonder if you're configuring Reprint differently than I expect. 
1. Can you check your merged manifest to make sure `<uses-permission android:name="android.permission.USE_FINGERPRINT"/>` is included?
2.  Can you check that you're only calling `Reprint.initialize` before any other calls to `Reprint`, and only once in the lifetime of the process (e.g. in `Application.onCreate`, not on `Activity.onCreate`)?
3. Are you including the SPass module?

**Closed** 2017-12-25 01:25 UTC

**Comment by pgrpmichel** [comment] 2018-01-05 21:15
1. Can you check your merged manifest to make sure <uses-permission android:name="android.permission.USE_FINGERPRINT"/> is included?
 - Yes, it's there (required=false)
2. Can you check that you're only calling Reprint.initialize before any other calls to Reprint, and only once in the lifetime of the process (e.g. in Application.onCreate, not on Activity.onCreate)?
 - Just once, in Application.onCreate().
3. Are you including the SPass module?
 - Yes, we're including the SPass module.
4. Are you calling isHardwarePresent before hasFingerprintRegistered? If so, does it return true or false?
- Yes, we call isHardwarePresent before hasFingerprintRegistered.  Based on the crash, I'm assuming it returns true, but would know better if I could test against a device that causes the crash.  Unfortunately, I don't have access to one at this time.

**Comment by ajalt** [comment] 2018-01-08 17:02
Thanks for the info! Let me know if you're still seeing issues with the latest version of Reprint.
